#!/usr/bin/env python3

import os, sys

from os import listdir
from os.path import isfile, join
from random import randint

directory = sys.argv[1]
files = [f for f in listdir(directory) if isfile(join(directory, f))]

for file in files:
    try:
        content = None
        randn = randint(100000, 99999999999)
        newname = f"{randn}.{file.split('.')[1]}" 

        os.rename(file, newname)

    except:
        print(f'Failed to rename file {file}')
        continue
